/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the LocoLaser tool.
 * It should not be modified by hand.
 */

import Foundation

public class Str {

    /// LocoLaser example
    public static var app_name : String {
        get {
            return NSLocalizedString("app_name", tableName:"Localizable", bundle:Bundle.main, value:"LocoLaser example", comment: "LocoLaser example")
        }
    }

    /// This is example application of how to use the LocoLser.
    public static var screen_main_app_description : String {
        get {
            return NSLocalizedString("screen_main_app_description", tableName:"Localizable", bundle:Bundle.main, value:"This is example application of how to use the LocoLser.", comment: "This is example application of how to use the LocoLser.")
        }
    }

    /// Plural string examples
    public static var screen_main_plural_example_title : String {
        get {
            return NSLocalizedString("screen_main_plural_example_title", tableName:"Localizable", bundle:Bundle.main, value:"Plural string examples", comment: "Plural string examples")
        }
    }

    /// Other: %d values
    public static var screen_main_plural_string : String {
        get {
            return NSLocalizedString("screen_main_plural_string", tableName:"Localizable", bundle:Bundle.main, value:"Other: %d values", comment: "Other: %d values")
        }
    }

}